# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/cloudsite.js
#####

SDLC_CLOUDSITE_JS:=$(DIST)/cloudsite.js
SDLC_CLOUDSITE_JS_ENTRY=$(SRC)/lib/index.mjs
BUILD_TARGETS+=$(SDLC_CLOUDSITE_JS)

$(SDLC_CLOUDSITE_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_CLOUDSITE_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/cloudsite.js
#####
